# JWT
jwt:
  secret: 'f2cb77d3-05a7-4813-bd52-f14a4a68f0f3'
  # 30 天
  expires: '30d'

# cookie
cookie:
  key: 'bszhct-admin-local'
  secret: '949ec992-2ebf-4e40-9141-c79754141ec4'
  domain: '192.168.1.101'
  # 30 天
  maxAge: 2592000000

# 服务配置
server:
  port: 9302
  hostname: '0.0.0.0'
  apiPrefix: '/api'
  # 鉴权白名单
  authWhitelist:
    - '/api/v1/admin/mockLogin'
    - '/api/v1/admin/login'
    - '/api/v1/admin/logout'
  # 响应数据白名单
  responseDataWhitelist:
  # 跨域白名单
  allowlist:
    - 'http://192.168.1.101:9201'
    - 'https://test.admin.bszhct.com'
